export const primeVueComponentNames = [
  'AutoComplete',
  'Calendar',
  'CascadeSelect',
  'Checkbox',
  'Chips',
  'ColorPicker',
  'Dropdown',
  'Editor',
  'InputMask',
  'InputNumber',
  'InputSwitch',
  'InputText',
  'Knob',
  'Listbox',
  'MultiSelect',
  'Password',
  'RadioButton',
  'Rating',
  'SelectButton',
  'Slider',
  'Textarea',
  'ToggleButton',
  'TreeSelect',
  'TriStateCheckbox',
  'Button',
  'SplitButton',
  'DataTable',
  'Column',
  'ColumnGroup',
  'DataView',
  'FullCalendar',
  'OrderList',
  'OrganizationChart',
  'Paginator',
  'PickList',
  'Timelist',
  'Tree',
  'TreeTable',
  'Accordion',
  'AccordionTab',
  'Card',
  'DeferredContent',
  'Divider',
  'Fieldset',
  'Panel',
  'Splitter',
  'SplitterPanel',
  'ScrollPanel',
  'TabView',
  'TabPanel',
  'Toolbar',
  'ConfirmDialog',
  'ConfirmPopup',
  'Dialog',
  'OverlayPanel',
  'Sidebar',
  'Tooltip',
  'FileUpload',
  'Breadcrumb',
  'ContextMenu',
  'MegaMenu',
  'Menu',
  'Menubar',
  'PanelMenu',
  'Steps',
  'TabMenu',
  'TieredMenu',
  'Chart',
  'Message',
  'Toast',
  'Carousel',
  'Galleria',
  'Avatar',
  'AvatarGroup',
  'Badge',
  'Chip',
  'BlockUI',
  'Inplace',
  'ScrollTop',
  'Skeleton',
  'ProgressBar',
  'ProgressSpiner',
  'Tag',
  'Terminal',
  'TerminalService',
]

// export const PrimeVueResolver = (name) => {
//   if (components.includes(name)) {
//     return {
//       path: `primevue/${name}/${name}.vue`,
//     }
//   }
// }
